### ISSUE TITLE
Handle specific Gitlab repos only?

### ISSUE THREAD

**Issue by db4** [bozaro/git-as-svn#183]
I would love to grant SVN access to a limited number of Gitlab-served repos  and don't expose via SVN everything else. Is it possible? Unfortunately docs are very unclear on that.  My current config is:
```
# Use GitLab repositories
repositoryMapping: !gitlabMapping
  path: /var/opt/gitlab/git-data/repositories/
  template:
    branch: master
    renameDetection: true

# Use GitLab user database
userDB: !gitlabUsers {}
```
and all Gitlab repos are accessible via SVN
