### ISSUE TITLE
Expose via SVN different branches of a GitLab repo?

### ISSUE THREAD

**Issue by db4** [bozaro/git-as-svn#188]
I know git-as-svn does not support (yet) multiple SVN branches layout; [this issue](https://github.com/bozaro/git-as-svn/issues/69) recommends
>   create many svn-repositories for one git-repositry (one repo per branch)

as a workaround. Is it possible for GitLab repos? If yes, can you share an example config doing that?

**Comment by slonopotamus** [comment]
No, it is currently impossible to expose multiple branches of a single repo when using `!gitlabMapping`.

**Comment by db4** [comment]
Can you recommend any workaround? I would shutdown a remaining svn repo and move to git completely  but  svn users need to access multiple branches.

**Comment by slonopotamus** [comment]
Multiple branches per repo are currently only supported for `repositoryMapping: !listMapping`.

However, `listMapping`
1. Doesn't support auto-discovery of newly-created repositories/branches and requires manual config editing and git-as-svn restart when repository list changes.
2. Doesn't support checking user access rights via GitLab, you'll need to specify ACL directly in git-as-svn config. See `repositoryMapping` section in https://github.com/bozaro/git-as-svn/blob/master/cfg/config-local.example

**Comment by db4** [comment]
I've finally found some time to try this approach out. Unfortunately it's not going to work with GitLab-hosted repos. Here is a my config:

```
repositoryMapping: !listMapping
  repositories:
    test-master:
      access: !acl
        groups:
          - name: developers
            users:
              - test
        access:
          - path: /
            allowed:
              - '@developers'
      repository: !git
        pusher: !pushEmbedded
          update: update
          preReceive: pre-receive
          postReceive: post-receive
        createMode: EXAMPLE
        branch: master
        path: /var/opt/gitlab/git-data/repositories/test/test.git
        renameDetection: true

    test-branch:
      access: !acl
        groups:
          - name: developers
            users:
              - test
        access:
          - path: /
            allowed:
              - '@developers'
      repository: !git
        pusher: !pushEmbedded
          update: update
          preReceive: pre-receive
          postReceive: post-receive
        createMode: EXAMPLE
        branch: branches/branch
        path: /var/opt/gitlab/git-data/repositories/test/test.git
        renameDetection: true

userDB: !gitlabUsers {}
```

This way I was able to checkout the repo via SVN, but when I try commit something it fails with
```
Transmitting file data .done
Committing transaction...
svn: E165001: Commit failed (details follow):
svn: E165001: svn: E165001: Hook /var/opt/gitlab/git-data/repositories/test/test.git/hooks/pre-receive failed with output:
GitLab: The project you were looking for could not be found.
```

Probably, there is something special in GitLab hooks (some env vars should be set?). Any thoughts on how to make it work?
